# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.20.2
yarn_mappings=1.20.2+build.4
loader_version=0.18.4
# Mod Properties
mod_version=1.0.1
maven_group=net.fenrir
archives_base_name=theplaneswalker
# Dependencies
origins_version=1.12.10
apoli_version=2.11.11
calio_version=1.13.3
cca_version=2.8.1
reach_version=1.1.1
ffl_version=3.0.0-beta.2
clothconfig_version=4.11.14
modmenu_version=2.0.12
fabric_version=0.91.6+1.20.2
# License Stuff
owners=SciRave, fordz0
license_header=LICENSE_HEADER
display_name=Origins: Planeswalker Reborn
version=1.0.0
